export function generateID() {
    // https://stackoverflow.com/a/8084248/4333479
    return (Math.random() + 1).toString(16).substring(2);
}


const firstNames = [
    'Adam',
    'Bob',
    'Carly',
    'Diana',
    'Eleanor',
    'Fiona',
    'Gregory',
    'Horatio',
    'Inigo',
    'Janet',
    'Kyle',
    'Linus',
    'Michael',
    'Nadia',
    'Olberic',
    'Patricia',
    'Quinton',
    'Rudolph',
    'Sahara',
    'Tomathy',
    'Ulysses',
    'Valerie',
    'Wanda',
    'Xander',
    'Yale',
    'Zagreus'
];

// These are the most common last names for each letter of the alphabet,
// with the exception of 'Quackenbush', which was ranked 10th but also
// sounded really funny to me.
const lastNames = [
    'Anderson',
    'Brown',
    'Clark',
    'Davis',
    'Evans',
    'Fisher',
    'Green',
    'Harris',
    'Ingram',
    'Johnson',
    'King',
    'Lewis',
    'Miller',
    'Nelson',
    'Olson',
    'Peterson',
    'Quackenbush',
    'Robinson',
    'Smith',
    'Taylor',
    'Underwood',
    'Vaughn',
    'Williams',
    'Xavier',
    'Young',
    'Zimmerman'
];

// Assembled by picking random street names from around the Vancouver-Portland
// area.
const streetNames = [
    'Main St',
    'St Johns Rd',
    '4th Plain Blvd',
    'Mill Plain Blvd',
    'Salmon Creek Ave',
    'Padden Pkwy',
    'Help I\'m Trapped On An Urban Planning Committee Blvd',
    'Glisan St',
    'Division St',
    'Burnside Rd',
    '139th St',
    '48th Pl',
    '72nd Ave',
    'St Helens Ave',
    'Killingsworth St',
    'Fremont St',
    'Broadway',
    'Burnside St',
    'Belmont St',
    'Stark St',
    'Division St',
    'Steele St'
];

// From Wikipedia
// https://en.wikipedia.org/wiki/List_of_municipalities_in_Washington#List_of_cities
const townNames = [
    'Aberdeen, WA',
    'Airway Heights, WA',
    'Algona, WA',
    'Anacortes, WA',
    'Arlington, WA',
    'Asotin, WA',
    'Auburn, WA',
    'Pierce, WA',
    'Bainbridge Island, WA',
    'Battle Ground, WA',
    'Bellevue, WA',
    'Bellingham, WA',
    'Benton City, WA',
    'Bingen, WA',
    'Black Diamond, WA',
    'Blaine, WA',
    'Bonney Lake, WA',
    'Bothell, WA',
    'Snohomish, WA',
    'Bremerton, WA',
    'Brewster, WA',
    'Bridgeport, WA',
    'Brier, WA',
    'Buckley, WA',
    'Burien, WA',
    'Burlington, WA',
    'Camas, WA',
    'Carnation, WA',
    'Cashmere, WA',
    'Castle Rock, WA',
    'Centralia, WA',
    'Chehalis, WA',
    'Chelan, WA',
    'Cheney, WA',
    'Chewelah, WA',
    'Clarkston, WA',
    'Cle Elum, WA',
    'Clyde Hill, WA',
    'Colfax, WA',
    'College Place, WA',
    'Colville, WA',
    'Connell, WA',
    'Cosmopolis, WA',
    'Covington, WA',
    'Davenport, WA',
    'Dayton, WA',
    'Deer Park, WA',
    'Des Moines, WA',
    'DuPont, WA',
    'Duvall, WA',
    'East Wenatchee, WA',
    'Edgewood, WA',
    'Edmonds, WA',
    'Electric City, WA',
    'Ellensburg, WA',
    'Elma, WA',
    'Entiat, WA',
    'Enumclaw, WA',
    'Pierce, WA',
    'Ephrata, WA',
    'Everett, WA',
    'Everson, WA',
    'Federal Way, WA',
    'Ferndale, WA',
    'Fife, WA',
    'Fircrest, WA',
    'Forks, WA',
    'George, WA',
    'Gig Harbor, WA',
    'Gold Bar, WA',
    'Goldendale, WA',
    'Grand Coulee, WA',
    'Grandview, WA',
    'Granger, WA',
    'Granite Falls, WA',
    'Harrington, WA',
    'Hoquiam, WA',
    'Ilwaco, WA',
    'Issaquah, WA',
    'Kahlotus, WA',
    'Kalama, WA',
    'Kelso, WA',
    'Kenmore, WA',
    'Kennewick, WA',
    'Kent, WA',
    'Kettle Falls, WA',
    'Kirkland, WA',
    'Kittitas, WA',
    'La Center, WA',
    'Lacey, WA',
    'Lake Forest Park, WA',
    'Lake Stevens, WA',
    'Lakewood, WA',
    'Langley, WA',
    'Leavenworth, WA',
    'Liberty Lake, WA',
    'Long Beach, WA',
    'Longview, WA',
    'Lynden, WA',
    'Lynnwood, WA',
    'Mabton, WA',
    'Maple Valley, WA',
    'Marysville, WA',
    'Mattawa, WA',
    'McCleary, WA',
    'Medical Lake, WA',
    'Medina, WA',
    'Mercer Island, WA',
    'Mesa, WA',
    'Mill Creek, WA',
    'Millwood, WA',
    'Milton, WA',
    'King, WA',
    'Monroe, WA',
    'Montesano, WA',
    'Morton, WA',
    'Moses Lake, WA',
    'Mossyrock, WA',
    'Mount Vernon, WA',
    'Mountlake Terrace, WA',
    'Moxee, WA',
    'Mukilteo, WA',
    'Napavine, WA',
    'Newcastle, WA',
    'Newport, WA',
    'Nooksack, WA',
    'Normandy Park, WA',
    'North Bend, WA',
    'North Bonneville, WA',
    'Oak Harbor, WA',
    'Oakville, WA',
    'Ocean Shores, WA',
    'Okanogan, WA',
    'Olympia, WA',
    'Omak, WA',
    'Oroville, WA',
    'Orting, WA',
    'Othello, WA',
    'Pacific, WA',
    'Pierce, WA',
    'Palouse, WA',
    'Pasco, WA',
    'Pateros, WA',
    'Pomeroy, WA',
    'Port Angeles, WA',
    'Port Orchard, WA',
    'Port Townsend, WA',
    'Poulsbo, WA',
    'Prescott, WA',
    'Prosser, WA',
    'Pullman, WA',
    'Puyallup, WA',
    'Quincy, WA',
    'Rainier, WA',
    'Raymond, WA',
    'Redmond, WA',
    'Renton, WA',
    'Republic, WA',
    'Richland, WA',
    'Ridgefield, WA',
    'Ritzville, WA',
    'Rock Island, WA',
    'Roslyn, WA',
    'Roy, WA',
    'Royal City, WA',
    'Ruston, WA',
    'Sammamish, WA',
    'SeaTac, WA',
    'Seattle, WA',
    'Sedro-Woolley, WA',
    'Selah, WA',
    'Sequim, WA',
    'Shelton, WA',
    'Shoreline, WA',
    'Snohomish, WA',
    'Snoqualmie, WA',
    'Soap Lake, WA',
    'South Bend, WA',
    'Spangle, WA',
    'Spokane, WA',
    'Spokane Valley, WA',
    'Sprague, WA',
    'Stanwood, WA',
    'Stevenson, WA',
    'Sultan, WA',
    'Sumas, WA',
    'Sumner, WA',
    'Sunnyside, WA',
    'Tacoma, WA',
    'Tekoa, WA',
    'Tenino, WA',
    'Tieton, WA',
    'Toledo, WA',
    'Tonasket, WA',
    'Toppenish, WA',
    'Tukwila, WA',
    'Tumwater, WA',
    'Union Gap, WA',
    'University Place, WA',
    'Vader, WA',
    'Vancouver, WA',
    'Waitsburg, WA',
    'Walla Walla, WA',
    'Wapato, WA',
    'Warden, WA',
    'Washougal, WA',
    'Wenatchee, WA',
    'West Richland, WA',
    'Westport, WA',
    'White Salmon, WA',
    'Winlock, WA',
    'Woodinville, WA',
    'Woodland, WA',
    'Clark, WA',
    'Woodway, WA',
    'Yakima, WA',
    'Yelm, WA',
    'Zillah, WA',
]

const companyNames = [
    'Don\'s Fingerless Mittens, LLC',
    'BeepoVac Corp.',
    'Chalupa Gong',
    'Pear',
    'National Aeronautics and Sloths Administration',
    'Taste\'s Photographs',
    '8-Twelve',
    'Rectangular Table Pizza',
]

export function generateUserName() {
    const f = pickRandomElement(firstNames);
    const l = pickRandomElement(lastNames);
    return `${f} ${l}`;
}

export function generateAddress() {
    const num = Math.floor(Math.random() * 9999);
    const st = pickRandomElement(streetNames);
    return `${num} ${st}`;
}

export function generateTownName() {
    return pickRandomElement(townNames);
}

export function generateAreaCode() {
    return Math.floor(Math.random() * 9999) + 1000;
}

export function generateCompanyName() {
    return pickRandomElement(companyNames);
}

function pickRandomElement(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}